### ISSUE TITLE
Instance Representation

### ISSUE THREAD

**Issue by Davidyao99** [shiyoung77/OVIR-3D#2]
Hi, just wanted to confirm my understanding, but it seems like the 3d instance segmentations having overlapping points? Is this meant to be the case? i.e each point in the point cloud can be assigned to multiple instance segmentations?

**Comment by shiyoung77** [comment]
Yes. It is meant to be the case for our open-vocabulary setup. For example, points belonging to the "bottle cap" should also belong to the "bottle". The ground-truth annotation, however, does not have overlapping instances.
