### ISSUE TITLE
Empty mask error

### ISSUE THREAD

**Issue by Davidyao99** [shiyoung77/OVIR-3D#3]
Hi, I notice that the current algorithm throws an error when it receives a frame of Detic prediction that is nothing. 

`Traceback (most recent call last):
  File "/mnt/src/proposed_fusion.py", line 633, in <module>
    main()
  File "/mnt/src/proposed_fusion.py", line 599, in main
    instance_pt_count, instance_features, instance_detections = instance_fusion(
  File "/mnt/src/proposed_fusion.py", line 283, in instance_fusion
    pred_masks = resolve_overlapping_masks(pred_masks, pred_scores, device=device)
  File "/mnt/src/proposed_fusion.py", line 233, in resolve_overlapping_masks
    indices = ((scores == torch.max(scores, dim=0, keepdim=True).values) & pred_masks).nonzero()
IndexError: max(): Expected reduction dim 0 to have non-zero size.`

How should I resolve this bug? I was thinking of simply skipping this iteration if mask dimension is 0, but I am not sure if it will mess up the rest of the algorithm. Thanks!

**Comment by shiyoung77** [comment]
Yes, you can simply skip this iteration. I don't think it will affect much.

BTW, which scene is this?

**Comment by Davidyao99** [comment]
scene0304_00 and some other scenes. Hopefully I ran your code correctly. Hoping to better understand your algorithm with the evaluation code! Looking forward to it ;))

Thanks for all the help!
