### ISSUE TITLE
Understanding Filter by Instance Size

### ISSUE THREAD

**Issue by Davidyao99** [shiyoung77/OVIR-3D#5]
Hi, thank you so much for updating your codebase and fixing the issues!

I wanted to ask about the recent change that led to the drastic improvement. 
Besides changing the depth threshold for occlusion detection, the filtering by size is changed from a fixed value to using the median. Does this mean that roughly half the instances are removed each filtering round?

**Comment by shiyoung77** [comment]
No, the size of instance A will not affect the filtering result of instance B. They are independent. 

So basically, the size of a 3D instance segment will grow when more views (partial 3D segments projected from 2D) of this instance are integrated. We compute the median size of those projected 3D segments (~ the average size of this instance from a single view). Points in a 3D instance segment will be filtered when their detection rate is below a threshold. If the number of remaining points is less than the median size, then the entire instance segment is removed. The intuition is that the size of arbitrary instances may differ a lot and a universal threshold does not work.

**Comment by Davidyao99** [comment]
I see, that makes sense! Thank you!
