### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by Davidyao99** [shiyoung77/OVIR-3D#6]
hi, thank you so much for releasing your evaluation  code!

I am running your evaluation code, but I seem to be receiving nan values. Any idea why this might be happening?

![image](https://github.com/shiyoung77/OVIR-3D/assets/52120948/3468a987-4426-48b1-9731-3a6a03a4797f)

I am using a subset of the entire validation set. So perhaps that might be leading to the issue?

**Comment by shiyoung77** [comment]
Since you only evaluate on a subset, some categories may contain nan values. Perhaps change `np.mean` to `np.nanmean` at line 313,314,324 and see if that works?
https://github.com/shiyoung77/OVIR-3D/blob/main/src/eval_instance_retrieval_scannet200.py#L313

**Comment by Davidyao99** [comment]
Yup yup, you are right, I figured it out! Thank you so much ;')))
